#
# This docker image contains 
# * python3
# * git, curl, wget, graphviz, imagemagick
# * Data Science tools: dvc, snakemake, mlflow
# * supplemental: hugo, slackr, plantuml
#

# Ubuntu 20.04 (focal)
# https://hub.docker.com/_/ubuntu/?tab=tags&name=focal
# OS/ARCH: linux/amd64
FROM ubuntu:focal-20200703@sha256:d5a6519d9f048100123c568eb83f7ef5bfcad69b01424f420f17c932b00dea76

MAINTAINER cdeck3r

ENV SUPPLEMENTAL_DIR=/opt/smeter \
    INSTALL_SCRIPT=install_supplementals.sh

# Fix DL4006
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root
ENV DEBIAN_FRONTEND noninteractive

#
# add other things if required
#
RUN apt-get update \
    && apt-get install -yq --no-install-recommends \
        wget \
        bzip2 \
        ca-certificates \
        sudo \
        locales \
        fonts-liberation \
        run-one \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen

#
# standard tools
#
RUN apt-get update && apt-get install -y \
        build-essential \
        default-jre \
        python3 python3-pip python3-setuptools \
        libxml2-dev libxslt-dev python3-dev python3-lxml \
        git \
        curl \
        wget \
        unzip \
        graphviz libgraphviz-dev pkg-config \
        imagemagick imagemagick-doc \ 
    && apt-get clean && rm -rf /var/lib/apt/lists/* 

#
# data science tools
#
RUN	pip3 install \
    dvc \
    snakemake \
    mlflow \
    pygraphviz \
    pygments

#
# supplemental software
#
COPY ${INSTALL_SCRIPT} /tmp
RUN mkdir -p ${SUPPLEMENTAL_DIR} \
    && cp /tmp/${INSTALL_SCRIPT} $SUPPLEMENTAL_DIR \
    && ${SUPPLEMENTAL_DIR}/${INSTALL_SCRIPT}

WORKDIR ${SUPPLEMENTAL_DIR}

CMD ["/bin/bash"]