from snakemake.utils import validate, min_version
##### set minimum snakemake version #####
min_version("5.1.2")

##### variables #####

PROJECT_DIR="/SmartMeter"
DOCS_DIR=PROJECT_DIR+"/docs"
DOCS_SITE=PROJECT_DIR+"/docs_site"

SUPPLEMENTAL_DIR="/opt/smeter"
HUGO=SUPPLEMENTAL_DIR+"/hugo/hugo"
PLANTUML_JAR=SUPPLEMENTAL_DIR+"/plantuml/plantuml.jar"

##### target rules #####



##### load rules #####

include: "doc.snakefile"

